version: '2'
services:
  sensors:    
    build: ./sensors
    container_name: sensors
    privileged: true
    # labels:
    #   io.balena.features.kernel-modules: '1'
    #   io.balena.features.firmware: '1'
    #   io.balena.features.dbus: '1'
    # devices:
    #   - "/dev/i2c-1:/dev/i2c-1"
    #   - "/dev/mem:/dev/mem"
    #   - "/sys:/sys"
    cap_add: 
      - SYS_RAWIO
    ports:
      - "8888:8888"
  display:    
    build: ./display
    container_name: display
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
      - "/sys:/sys"
    links:
      - "sensors"
    depends_on:
      - sensors  
