version: '2'
services:
  sensor-service:    
    build: ./sensor
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
    devices: 
      - "/dev/i2c-1:/dev/i2c-1" 
      - "/dev/mem:/dev/mem" 
    expose:
      - "8888"


    